import streamlit as st
from google import genai
from google.genai import types
import smtplib
from email.message import EmailMessage

from prompts import (
    SYSTEM_PROMPT,
    WELCOME_MESSAGE_TEMPLATE,
    STUDY_MODES,
    SUMMARY_REQUEST_PROMPT,
)


# -----------------------------
# Page configuration
# -----------------------------
st.set_page_config(
    page_title="StudySnap AI",
    page_icon="📚",
    layout="centered",
)


# -----------------------------
# Gemini configuration
# -----------------------------
GEMINI_API_KEY = st.secrets["GEMINI_API_KEY"]

MODEL_NAME = "gemini-3.6-flash"


@st.cache_resource
def get_gemini_client():
    return genai.Client(api_key=GEMINI_API_KEY)

def send_study_summary(summary,recipient_email):
    sender_email = st.secrets["GMAIL_ADDRESS"]
    app_password = st.secrets["GMAIL_APP_PASSWORD"].replace(" ", "")

    message = EmailMessage()

    message["Subject"] = "📚 Your StudySnap AI Study Summary"
    message["From"] = sender_email
    message["To"] = recipient_email

    message.set_content(
        f"""StudySnap AI - Study Summary

{summary}

--------------------------------
Generated by StudySnap AI
Snap it. Understand it. Master it.
"""
    )

    with smtplib.SMTP_SSL(
        "smtp.gmail.com",
        465
    ) as smtp:

        smtp.login(
            sender_email,
            app_password
        )

        smtp.send_message(message)

gemini_client = get_gemini_client()


# -----------------------------
# Session state
# -----------------------------
if "messages" not in st.session_state:
    st.session_state.messages = []


if "chat" not in st.session_state:
    st.session_state.chat = gemini_client.chats.create(
        model=MODEL_NAME,
        config=types.GenerateContentConfig(
            system_instruction=SYSTEM_PROMPT
        ),
    )


# -----------------------------
# Header
# -----------------------------
st.title("📚 StudySnap AI")
st.caption("Snap it. Understand it. Master it.")

student_name = st.text_input(
    "👤 Your Name",
    placeholder="Enter your name",
)


st.sidebar.header("🎯 Study Mode")

study_mode = st.sidebar.selectbox(
    "Choose how StudySnap should help you:",
    [
        "🧠 Explain",
        "📝 Summarize",
        "❓ Quiz Me",
        "💼 Interview Prep",
    ],
)

st.sidebar.divider()

if st.sidebar.button("🆕 New Study Session"):
    st.session_state.messages = []

    st.session_state.chat = gemini_client.chats.create(
        model=MODEL_NAME,
        config=types.GenerateContentConfig(
            system_instruction=SYSTEM_PROMPT
        ),
    )

    st.rerun()

st.sidebar.divider()

st.sidebar.subheader("📖 Study Summary")

recipient_email = st.sidebar.text_input(
    "📧 Enter your Gmail address",
    placeholder="example@gmail.com"
)

if st.sidebar.button("📧 Send Summary to Gmail"):
    if not recipient_email:
        st.sidebar.warning("Please enter your Gmail address.")
    else:
        with st.spinner("Creating your study summary..."):
            try:
                summary_response = st.session_state.chat.send_message(
                    SUMMARY_REQUEST_PROMPT
                )

                summary = summary_response.text

                send_study_summary(summary,recipient_email)

                st.sidebar.success(
                    "✅ Study summary sent to your Gmail!"
                )

            except Exception as error:
                st.sidebar.error(
                    f"Unable to send email: {error}"
                )

# -----------------------------
# Welcome message
# -----------------------------
if not st.session_state.messages:
    welcome_message = WELCOME_MESSAGE_TEMPLATE.format(
        name="Student"
    )

    st.session_state.messages.append(
        {
            "role": "assistant",
            "content": welcome_message,
        }
    )


# -----------------------------
# Display previous messages
# -----------------------------
for message in st.session_state.messages:

    with st.chat_message(message["role"]):

        if message.get("image") is not None:
            st.image(message["image"])

        st.write(message["content"])


# -----------------------------
# Chat input + image upload
# -----------------------------
prompt = st.chat_input(
    "Ask a question or upload a study image...",
    accept_file=True,
    file_type=["jpg", "jpeg", "png"],
)


# -----------------------------
# Handle user input
# -----------------------------
if prompt:

    user_text = prompt.text
    uploaded_files = prompt.files

    # Get first uploaded image
    image_file = uploaded_files[0] if uploaded_files else None

    # -----------------------------
    # Prepare user's message
    # -----------------------------
    message_content = user_text

    if not message_content:
        message_content = "Please analyze this study image."

    # -----------------------------
    # Study mode instruction
    # -----------------------------
    mode_instruction = STUDY_MODES[study_mode]

    final_prompt = f"""
Study Mode: {study_mode}

{mode_instruction}

Student's request:
{message_content}
"""

    # -----------------------------
    # Show user message
    # -----------------------------
    with st.chat_message("user"):

        if image_file:
            st.image(image_file)

        st.write(message_content)

    # -----------------------------
    # Save user message
    # -----------------------------
    user_message = {
        "role": "user",
        "content": message_content,
    }

    if image_file:
        user_message["image"] = image_file

    st.session_state.messages.append(user_message)

    # -----------------------------
    # Send to Gemini
    # -----------------------------
    with st.chat_message("assistant"):

        with st.spinner("📖 Studying your material..."):

            try:

                if image_file:

                    image_bytes = image_file.getvalue()

                    image_part = types.Part.from_bytes(
                        data=image_bytes,
                        mime_type=image_file.type,
                    )

                    response = st.session_state.chat.send_message(
                        [
                            image_part,
                            final_prompt,
                        ]
                    )

                else:

                    response = st.session_state.chat.send_message(
                        final_prompt
                    )

                answer = response.text

                st.write(answer)

                # -----------------------------
                # Save assistant response
                # -----------------------------
                st.session_state.messages.append(
                    {
                        "role": "assistant",
                        "content": answer,
                    }
                )

            except Exception as error:

                st.error(
                    f"Something went wrong: {error}"
                )


    